
package org.virtualsolar.vso.vsoi;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "VSOiService", targetNamespace = "http://virtualsolar.org/VSO/VSOi", wsdlLocation = "http://vso.tuc.noao.edu/VSO/WSDL/VSOi_rpc_literal.wsdl")
public class VSOiService
    extends Service
{

    private final static URL VSOISERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.virtualsolar.vso.vsoi.VSOiService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.virtualsolar.vso.vsoi.VSOiService.class.getResource(".");
            url = new URL(baseUrl, "http://vso.tuc.noao.edu/VSO/WSDL/VSOi_rpc_literal.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://vso.tuc.noao.edu/VSO/WSDL/VSOi_rpc_literal.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        VSOISERVICE_WSDL_LOCATION = url;
    }

    public VSOiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VSOiService() {
        super(VSOISERVICE_WSDL_LOCATION, new QName("http://virtualsolar.org/VSO/VSOi", "VSOiService"));
    }

    /**
     * 
     * @return
     *     returns VSOiPort
     */
    @WebEndpoint(name = "nsoTestVSOi")
    public VSOiPort getNsoTestVSOi() {
        return super.getPort(new QName("http://virtualsolar.org/VSO/VSOi", "nsoTestVSOi"), VSOiPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VSOiPort
     */
    @WebEndpoint(name = "nsoTestVSOi")
    public VSOiPort getNsoTestVSOi(WebServiceFeature... features) {
        return super.getPort(new QName("http://virtualsolar.org/VSO/VSOi", "nsoTestVSOi"), VSOiPort.class, features);
    }

    /**
     * 
     * @return
     *     returns VSOiPort
     */
    @WebEndpoint(name = "nsoVSOi")
    public VSOiPort getNsoVSOi() {
        return super.getPort(new QName("http://virtualsolar.org/VSO/VSOi", "nsoVSOi"), VSOiPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VSOiPort
     */
    @WebEndpoint(name = "nsoVSOi")
    public VSOiPort getNsoVSOi(WebServiceFeature... features) {
        return super.getPort(new QName("http://virtualsolar.org/VSO/VSOi", "nsoVSOi"), VSOiPort.class, features);
    }

}
